### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by JaviGomez02** [JaviGomez02/Playlist#1]
Ya he terminado el trabajo personal. Miralo por si no está bien o por si me falta algo

**Comment by ioliasa** [comment]
Javier esta mañana te he enviado un Issue respondiendo a esto, pero a saber a quién se lo he puesto porque efectivamente aquí no está. El proyecto está bien, y como es bastante largo para añadir la base de datos es suficiente con que hagas la parte de añadir autor, ver la información del autor, añadir a la play list y ver la play list

**Comment by JaviGomez02** [comment]
Vale muchas gracias
